"use client";

import { useState } from "react";
import Image from "next/image";
import {
  Save,
  ExternalLink,
  Loader2,
  CheckCircle2,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { PlayButton } from "@/components/ui/play-button";
import { usePlayerOptional } from "@/providers/spotify-player-provider";

interface Track {
  uri: string;
  name: string;
  artist: string;
  album: string;
  image: string;
  previewUrl: string | null;
}

interface GeneratedPlaylistProps {
  tracks: Track[];
  mood: string;
  genre?: string;
  songCount: number;
}

export function GeneratedPlaylist({
  tracks,
  mood,
  genre,
  songCount,
}: GeneratedPlaylistProps) {
  const [saved, setSaved] = useState(false);
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [needsAuth, setNeedsAuth] = useState(false);
  const [playlistName, setPlaylistName] = useState(
    `MUSAI ${mood.charAt(0).toUpperCase() + mood.slice(1)} Mix`
  );

  const player = usePlayerOptional();
  const allUris = tracks.map((t) => t.uri);

  const handleSaveToSpotify = async () => {
    setSaveError(null);
    setNeedsAuth(false);
    setSaving(true);

    try {
      const resp = await fetch("/api/spotify/create-playlist", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: playlistName,
          description: `Generated by MUSAI - ${mood} mood${genre ? `, ${genre}` : ""}`,
          isPublic: false,
          trackUris: tracks.map((t) => t.uri),
        }),
      });

      const data = await resp.json().catch(() => ({}));

      if (resp.status === 401 && data.needsAuth) {
        setNeedsAuth(true);
        setSaveError("Authorize Spotify to save playlists with tracks.");
        return;
      }

      if (!resp.ok) {
        setSaveError(data.error || "Failed to save playlist.");
        return;
      }

      setSaved(true);
    } catch {
      setSaveError("Failed to save playlist.");
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="bg-card rounded-xl border border-border overflow-hidden">
      {/* Header */}
      <div className="p-6 border-b border-border">
        <div className="flex items-center justify-between">
          <div>
            <input
              value={playlistName}
              onChange={(e) => setPlaylistName(e.target.value)}
              className="text-lg font-bold text-foreground bg-transparent border-none outline-none focus:text-emerald-500 transition-colors"
            />
            <p className="text-sm text-muted-foreground mt-1">
              {tracks.length} tracks &middot; {mood}
              {genre ? ` &middot; ${genre}` : ""}
            </p>
          </div>
          <button
            onClick={handleSaveToSpotify}
            disabled={saving || saved}
            className={cn(
              "flex items-center gap-2 px-4 py-2 rounded-lg font-semibold text-sm transition-all",
              saved
                ? "bg-emerald-600/20 text-emerald-500 border border-emerald-800/30"
                : "bg-emerald-600 hover:bg-emerald-500 text-black"
            )}
          >
            {saving ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : saved ? (
              <CheckCircle2 className="w-4 h-4" />
            ) : (
              <Save className="w-4 h-4" />
            )}
            {saved ? "Saved!" : "Save to Spotify"}
          </button>
        </div>
        {saveError && (
          <div className="mt-2">
            <p className="text-xs text-red-500">{saveError}</p>
            {needsAuth && (
              <a
                href="/api/spotify/authorize"
                onClick={() => {
                  sessionStorage.setItem(
                    "musai_pending_playlist",
                    JSON.stringify({ tracks, mood, genre, songCount })
                  );
                }}
                className="inline-flex items-center gap-1.5 mt-2 px-3 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-black text-xs font-semibold rounded-lg transition-colors"
              >
                Authorize Spotify Playlist Access
              </a>
            )}
          </div>
        )}
      </div>

      {/* Track list */}
      <div className="divide-y divide-border">
        {tracks.map((track, index) => {
          const isCurrentTrack = player?.currentTrack?.uri === track.uri;

          return (
            <div
              key={track.uri}
              className={cn(
                "flex items-center gap-3 px-6 py-3 hover:bg-secondary/30 transition-colors group",
                isCurrentTrack && "bg-emerald-500/5"
              )}
            >
              <div className="w-6 text-center relative">
                <span
                  className={cn(
                    "text-xs text-muted-foreground",
                    player?.isReady && "group-hover:invisible"
                  )}
                >
                  {index + 1}
                </span>
                {player?.isReady && (
                  <div className="absolute inset-0 flex items-center justify-center invisible group-hover:visible">
                    <PlayButton
                      trackUri={track.uri}
                      trackUris={allUris}
                      offset={index}
                      size="sm"
                    />
                  </div>
                )}
              </div>

              <div className="relative w-10 h-10 rounded overflow-hidden flex-shrink-0">
                {track.image ? (
                  <Image
                    src={track.image}
                    alt={track.name}
                    fill
                    className="object-cover"
                  />
                ) : (
                  <div className="w-full h-full bg-secondary" />
                )}
              </div>

              <div className="flex-1 min-w-0">
                <p
                  className={cn(
                    "text-sm font-medium truncate transition-colors",
                    isCurrentTrack
                      ? "text-emerald-500"
                      : "text-foreground group-hover:text-emerald-500"
                  )}
                >
                  {track.name}
                </p>
                <p className="text-xs text-muted-foreground truncate">
                  {track.artist} &middot; {track.album}
                </p>
              </div>

              <a
                href={`https://open.spotify.com/track/${track.uri.split(":").pop()}`}
                target="_blank"
                rel="noopener noreferrer"
                className="text-muted-foreground hover:text-emerald-500 transition-colors opacity-0 group-hover:opacity-100"
              >
                <ExternalLink className="w-3.5 h-3.5" />
              </a>
            </div>
          );
        })}
      </div>
    </div>
  );
}
