"use client";

import { useState } from "react";
import Image from "next/image";
import { trpc } from "@/lib/trpc";
import {
  Save,
  ExternalLink,
  Play,
  Pause,
  Loader2,
  CheckCircle2,
} from "lucide-react";
import { cn } from "@/lib/utils";

interface Track {
  uri: string;
  name: string;
  artist: string;
  album: string;
  image: string;
  previewUrl: string | null;
}

interface GeneratedPlaylistProps {
  tracks: Track[];
  mood: string;
  genre?: string;
  songCount: number;
}

export function GeneratedPlaylist({
  tracks,
  mood,
  genre,
  songCount,
}: GeneratedPlaylistProps) {
  const [playingTrack, setPlayingTrack] = useState<string | null>(null);
  const [audioEl, setAudioEl] = useState<HTMLAudioElement | null>(null);
  const [saved, setSaved] = useState(false);
  const [playlistName, setPlaylistName] = useState(
    `MUSAI ${mood.charAt(0).toUpperCase() + mood.slice(1)} Mix`
  );

  const createPlaylistMutation = trpc.spotify.createPlaylist.useMutation({
    onSuccess: () => setSaved(true),
  });

  const togglePreview = (track: Track) => {
    if (!track.previewUrl) return;

    if (playingTrack === track.uri) {
      audioEl?.pause();
      setPlayingTrack(null);
      setAudioEl(null);
      return;
    }

    audioEl?.pause();
    const audio = new Audio(track.previewUrl);
    audio.play();
    audio.onended = () => {
      setPlayingTrack(null);
      setAudioEl(null);
    };
    setAudioEl(audio);
    setPlayingTrack(track.uri);
  };

  const handleSaveToSpotify = () => {
    createPlaylistMutation.mutate({
      name: playlistName,
      description: `Generated by MUSAI - ${mood} mood${genre ? `, ${genre}` : ""}`,
      isPublic: false,
      trackUris: tracks.map((t) => t.uri),
    });
  };

  return (
    <div className="bg-card rounded-xl border border-border overflow-hidden">
      {/* Header */}
      <div className="p-6 border-b border-border">
        <div className="flex items-center justify-between">
          <div>
            <input
              value={playlistName}
              onChange={(e) => setPlaylistName(e.target.value)}
              className="text-lg font-bold text-foreground bg-transparent border-none outline-none focus:text-emerald-500 transition-colors"
            />
            <p className="text-sm text-muted-foreground mt-1">
              {tracks.length} tracks &middot; {mood}
              {genre ? ` &middot; ${genre}` : ""}
            </p>
          </div>
          <button
            onClick={handleSaveToSpotify}
            disabled={createPlaylistMutation.isPending || saved}
            className={cn(
              "flex items-center gap-2 px-4 py-2 rounded-lg font-semibold text-sm transition-all",
              saved
                ? "bg-emerald-600/20 text-emerald-500 border border-emerald-800/30"
                : "bg-emerald-600 hover:bg-emerald-500 text-black"
            )}
          >
            {createPlaylistMutation.isPending ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : saved ? (
              <CheckCircle2 className="w-4 h-4" />
            ) : (
              <Save className="w-4 h-4" />
            )}
            {saved ? "Saved!" : "Save to Spotify"}
          </button>
        </div>
      </div>

      {/* Track list */}
      <div className="divide-y divide-border">
        {tracks.map((track, index) => (
          <div
            key={track.uri}
            className="flex items-center gap-3 px-6 py-3 hover:bg-secondary/30 transition-colors group"
          >
            <span className="w-6 text-center text-xs text-muted-foreground">
              {index + 1}
            </span>

            <button
              onClick={() => togglePreview(track)}
              disabled={!track.previewUrl}
              className="relative w-10 h-10 rounded overflow-hidden flex-shrink-0"
            >
              {track.image ? (
                <Image
                  src={track.image}
                  alt={track.name}
                  fill
                  className="object-cover"
                />
              ) : (
                <div className="w-full h-full bg-secondary" />
              )}
              {track.previewUrl && (
                <div className="absolute inset-0 bg-black/40 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                  {playingTrack === track.uri ? (
                    <Pause className="w-4 h-4 text-white" />
                  ) : (
                    <Play className="w-4 h-4 text-white" />
                  )}
                </div>
              )}
            </button>

            <div className="flex-1 min-w-0">
              <p
                className={cn(
                  "text-sm font-medium truncate transition-colors",
                  playingTrack === track.uri
                    ? "text-emerald-500"
                    : "text-foreground"
                )}
              >
                {track.name}
              </p>
              <p className="text-xs text-muted-foreground truncate">
                {track.artist} &middot; {track.album}
              </p>
            </div>

            <a
              href={`https://open.spotify.com/track/${track.uri.split(":").pop()}`}
              target="_blank"
              rel="noopener noreferrer"
              className="text-muted-foreground hover:text-emerald-500 transition-colors opacity-0 group-hover:opacity-100"
            >
              <ExternalLink className="w-3.5 h-3.5" />
            </a>
          </div>
        ))}
      </div>
    </div>
  );
}
